Django4/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from student import views
from student import urls as student_url
from teacher import urls as teacher_url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^index/', views.index),
    url(r'^reg/', views.register),
    url(r'^logout/', views.logout),
    url(r'^class/', include(student_url)),
    url(r'^teacher/', include(teacher_url)),
]

student/urls.py
from django.conf.urls import url
from student import views

urlpatterns = [

    url(r'course/(\d+)/', views.course),
    url(r'(\d+)/', views.classes),

]

teacher/urls.py
from django.conf.urls import url
from teacher import views

urlpatterns = [
    url(r'index/', views.index),
]

student/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Student(AbstractUser):
    num = models.AutoField(primary_key=True)
    # name = models.CharField(max_length=16)
    sex_choice = (('男', "man"), ('女', "women"))
    sex = models.CharField(max_length=10, choices=sex_choice)
    age = models.IntegerField(default=0)
    settime = models.DateTimeField(auto_now_add=True)
    addr = models.CharField(max_length=32)
    phone = models.CharField(max_length=32)
    course = models.OneToOneField(to="Course", to_field="num", null=True)
    classes = models.ForeignKey(to="Class", to_field="num", null=True)
    teacher = models.ForeignKey(to="Teacher", to_field="num", null=True)

    def __str__(self):
        return self.num


class Course(models.Model):
    num = models.AutoField(primary_key=True)
    english = models.IntegerField(default=0)
    chinese = models.IntegerField(default=0)
    math = models.IntegerField(default=0)
    phycics = models.IntegerField(default=0)

    def __str__(self):
        return self.chinese


class Class(models.Model):
    num = models.AutoField(primary_key=True)
    cname = models.CharField(max_length=32)
    teachers = models.ForeignKey(to="Teacher",to_field="num", null=True)

    def __str__(self):
        return self.cname


class Teacher(models.Model):
    num = models.AutoField(primary_key=True)
    tname = models.CharField(max_length=16)
    age = models.IntegerField(default=0)
    sex_choice = (("男", "man"), ("女", "woman"))
    sex = models.CharField(max_length=10, choices=sex_choice)
    phone = models.CharField(max_length=32)
    
    def __str__(self):
        return self.tname

teacher/models.py
from django.db import models

# Create your models here.

student/forms.py
from django import forms
from student import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator


class RegForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label="用户名",
        widget=forms.widgets.TextInput(attrs={"class": "form-control"},),
        error_messages={
            "max_length": "用户名最长16位",
            "required": "用户名不能为空",
        }
    )
    password = forms.CharField(
        min_length=6,
        max_length=10,
        label="密码",
        widget=forms.widgets.PasswordInput(attrs={"class": "form-control"},),
        error_messages={
            "max_length": "最小长度为6",
            "required": "密码不能为空",
        }
    )
    re_password = forms.CharField(
        min_length=6,
        max_length=10,
        label="确认密码",
        widget=forms.widgets.PasswordInput(attrs={"class": "form-control"}, render_value=True),
        error_messages={
            "min_length": "密码最少6位",
            "required": "密码不能为空",
        }
    )
    gender = forms.ChoiceField(
        choices=(('男', "男"), ('女', "女")),
        label="性别",
        initial=1,
        widget=forms.widgets.RadioSelect
    )
    age = forms.CharField(
        max_length=10,
        label="年龄",
        widget=forms.widgets.TextInput(attrs={"class": "form-control"}),

    )
    addr = forms.CharField(
        max_length=32,
        label="地址",
        widget=forms.widgets.TextInput(attrs={"class": "form-control"}),
        error_messages={
            "required": "地址不能为空",
        }
    )
    phone = forms.CharField(
        label="手机",
        validators=[
            RegexValidator(r'^1[3-9][0-9]{9}$', '手机格式不正确')
        ],
        widget=forms.widgets.TextInput(attrs={"class": "form-control"}),
        error_messages={
            "required": "手机不能为空"
        }
    )

    # 重写username字段的局部钩子
    def clean_username(self):
        username = self.cleaned_data.get("username")
        is_exist = models.Student.objects.filter(username=username)
        if is_exist:
            # 表示用户名已注册
            self.add_error("username", ValidationError("用户名已存在！"))
        else:
            return username

        # 重写全局的钩子函数， 对确认密码做效验
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")
        if re_password and re_password != password:
            self.add_error("re_password", ValidationError("两次密码不一致"))
        else:
            return self.cleaned_data

student/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from student import forms
from student import models

# Create your views here.


def login(request):
    if request.method == "POST":
        ret = {"status": 0, "msg": ""}
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        tname = models.Teacher.objects.values('tname')
        # print(tname.values(), tname)
        # print(user)
        if user:
            if username in [i['tname'] for i in tname]:
                auth.login(request, user)
                ret["msg"] = "/teacher/index/"
            else:
                # 用户名密码正确
                # 给用户做登录
                auth.login(request, user)  # 将登录用户赋值给request.user
                ret["msg"] = "/index/"
            return JsonResponse(ret)
        else:
            ret["status"] = 1
            ret["msg"] = "用户名或者密码错误！"
            return JsonResponse(ret)

    return render(request, 'login.html')


def register(request):
    form_obj = forms.RegForm()
    if request.method == "POST":
        form_obj = forms.RegForm(request.POST)
        # 让form帮我们做效验
        if form_obj.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            gender = request.POST.get("gender")
            age = request.POST.get("age")
            addr = request.POST.get("addr")
            phone = request.POST.get("phone")

            models.Student.objects.create_user(username=username, password=password, sex=gender, age=age, addr=addr, phone=phone)
            return redirect("/login/")
    return render(request, "register.html", {"form_obj": form_obj})


def logout(request):
    auth.logout(request)
    return render(request, 'login.html')


@login_required
def index(request):
    # print(request.user.username)
    user_message = models.Student.objects.filter(num=request.user.num).first()
    
    return render(request, "index.html", {"user_message": user_message})


def course(request, pk):
    # print(pk)
    class_message = models.Student.objects.filter(course_id=pk).first()
    # print(class_message)
    return render(request, 'course.html', {"class_message": class_message})


def classes(request, pk):
    print(pk)
    class_message = models.Student.objects.filter(classes_id=pk).first()
    # print(class_message)
    
    return render(request, 'classes.html', {"class_message": class_message,})

teacher/views.py
from django.shortcuts import render
from student import models

# Create your views here.


def index(request):
    print(request.user.num)
    teacher = models.Student.objects.filter(num=request.user.num)
    teacher_message = models.Teacher.objects.all()
    return render(request, 't_index.html', {"teacher": teacher, "teacher_message": teacher_message})

templates/base.html
<!DOCTYPE html>
<!-- saved from url=(0042)https://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>成绩</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/fontawesome/css/font-awesome.min.css">
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/teacher/index/">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Hi&nbsp;&nbsp;{{ teacher.username }}</a></li>
                <li><a href="/logout/">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar  high-top">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="">选课系统<span class="sr-only">(current)</span></a></li>
                <li class="active"><a href="/class/course/{{ class_message.pk }}/">成绩信息</a></li>
                <li class="active"><a href="/class/{{ class_message.pk }}/">班级信息</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">个人信息</h1>

            <div class="panel panel-primary">
                <!-- Default panel contents -->
                <div class="panel-heading">老师信息 <i class="fa fa-thumb-tack pull-right"></i></div>
                <div class="panel-body">
                    <div class="row" style="margin-bottom: 15px">
                        <form action="//" method="post">
                            <div class="col-md-4">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="select" placeholder="Search for...">
                                    <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">搜索</button>
                                </span>
                                </div><!-- /input-group -->
                            </div><!-- /.col-md-4 -->
                        </form>
                        <div class="col-md-1 pull-right">
                            <a href="#" type="button" class="btn btn-success" data-toggle="modal"
                               data-target="#myModal">新增</a>
                        </div>

                    </div><!-- /.row -->
                    <!--个人信息开始-->
                    {% block page-main %}

                    {% endblock %}
                   <!---个人信息结束-->
                </div>

            </div>
        </div>
    </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">添加信息</h4>
            </div>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/classes.html
<!DOCTYPE html>
<!-- saved from url=(0042)https://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">
    <title>班级</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/fontawesome/css/font-awesome.min.css">
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://v3.bootcss.com/examples/dashboard/#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Hi&nbsp;&nbsp;{{ class_message.username }}</a></li>
                <li><a href="/logout/">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar high-top">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="">选课系统<span class="sr-only">(current)</span></a></li>
                <li class="active"><a href="/class/course/{{ class_message.pk }}/">成绩信息</a></li>
                <li class="active"><a href="/class/{{ class_message.pk }}/">班级信息</a></li>
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">个人信息</h1>

            <div class="panel panel-primary">
                <!-- Default panel contents -->
                <div class="panel-heading">个人列表 <i class="fa fa-thumb-tack pull-right"></i></div>
                <div class="panel-body">
                    <div class="row" style="margin-bottom: 15px">
                        <form action="" method="get">
                            <div class="col-md-4">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="select" placeholder="Search for...">
                                    <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">搜索</button>
                                </span>
                                </div><!-- /input-group -->
                            </div><!-- /.col-md-4 -->
                        </form>
                        <div class="col-md-1 pull-right">
                            <a href="#" type="button" class="btn btn-success" data-toggle="modal"
                               data-target="#myModal">新增</a>
                        </div>
                    </div><!-- /.row -->
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>班级</th>
                            <th>用户名</th>
                            <th>英语</th>
                            <td>语文</td>
                            <td>数学</td>
                            <td>物理</td>
                            <td>班主任</td>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ class_message.classes.cname }}</td>
                            <td>{{ class_message.username }}</td>
                            <td>{{ class_message.course.english }}</td>
                            <td>{{ class_message.course.chinese }}</td>
                            <td>{{ class_message.course.math }}</td>
                            <td>{{ class_message.course.phycics }}</td>
                            <td>{{ class_message.teacher.tname }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">添加信息</h4>
            </div>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/course.html
<!DOCTYPE html>
<!-- saved from url=(0042)https://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>成绩</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/fontawesome/css/font-awesome.min.css">
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/index/">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Hi&nbsp;&nbsp;{{ class_message.username }}</a></li>
                <li><a href="/logout/">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar  high-top">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="">选课系统<span class="sr-only">(current)</span></a></li>
                <li class="active"><a href="/class/course/{{ class_message.pk }}/">成绩信息</a></li>
                <li class="active"><a href="/class/{{ class_message.pk }}/">班级信息</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">个人信息</h1>

            <div class="panel panel-primary">
                <!-- Default panel contents -->
                <div class="panel-heading">个人成绩 <i class="fa fa-thumb-tack pull-right"></i></div>
                <div class="panel-body">
                    <div class="row" style="margin-bottom: 15px">
                        <form action="//" method="post">
                            <div class="col-md-4">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="select" placeholder="Search for...">
                                    <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">搜索</button>
                                </span>
                                </div><!-- /input-group -->
                            </div><!-- /.col-md-4 -->
                        </form>
                        <div class="col-md-1 pull-right">
                            <a href="#" type="button" class="btn btn-success" data-toggle="modal"
                               data-target="#myModal">新增</a>
                        </div>

                    </div><!-- /.row -->

                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>id</th>
                            <th>用户名</th>
                            <th>英语</th>
                            <td>语文</td>
                            <td>数学</td>
                            <td>物理</td>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ class_message.num }}</td>
                            <td>{{ class_message.username }}</td>
                            <td>{{ class_message.course.english }}</td>
                            <td>{{ class_message.course.chinese }}</td>
                            <td>{{ class_message.course.math }}</td>
                            <td>{{ class_message.course.phycics }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">添加信息</h4>
            </div>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>

    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form novalidate action="/reg/" method="post" class="form-horizontal reg-form"> {# autocomplete="off"自动补全 #}
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}" class="col-sm-2 control-label">{{ form_obj.username.label }}</label>
                <div class="col-sm-10">
                    {{ form_obj.username }}
                    <span class="help-block">{{ form_obj.username.errors.0 }}</span>
                </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}" class="col-sm-2 control-label">{{ form_obj.password.label }}</label>
                <div class="col-sm-10">
                    {{ form_obj.password }}
                    <span class="help-block">{{ form_obj.password.errors.0 }}</span>
                </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.re_password.id_for_label }}" class="col-sm-2 control-label">{{ form_obj.re_password.label }}</label>
                <div class="col-sm-10">
                    {{ form_obj.re_password }}
                    <span class="help-block">{{ form_obj.re_password.errors.0 }}</span>
                </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.gender.id_for_label }}" class="col-sm-2 control-label">{{ form_obj.gender.label }}</label>
                <div class="col-sm-10">
                    {{ form_obj.gender }}
                    <span class="help-block">{{ form_obj.gender.errors.0 }}</span>
                </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.age.id_for_label }}" class="col-sm-2 control-label">{{ form_obj.age.label }}</label>
                <div class="col-sm-10">
                    {{ form_obj.age }}
                    <span class="help-block">{{ form_obj.age.errors.0 }}</span>
                </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.addr.id_for_label }}" class="col-sm-2 control-label">{{ form_obj.addr.label }}</label>
                <div class="col-sm-10">
                    {{ form_obj.addr }}
                    <span class="help-block">{{ form_obj.addr.errors.0 }}</span>
                </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.phone.id_for_label }}" class="col-sm-2 control-label">{{ form_obj.phone.label }}</label>
                <div class="col-sm-10">
                    {{ form_obj.phone }}
                    <span class="help-block">{{ form_obj.phone.errors.0 }}</span>
                </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success" id="reg-submit">注册</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
{#<script>#}
{#    // 找到头像的input标签绑定change事件#}
{#    $("#id_avatar").change(function(){#}
{#        //alert("123")#}
{#        // 1.读取你选中的那个文件#}
{#        var fileReader = new FileReader();#}
{#        // 取到你选中的那个文件#}
{#        //console.log(this.files[0]);#}
{#        //读取你选中的那个文件#}
{#        fileReader.readAsDataURL(this.files[0]);// 读取文件是需要时间的#}
{#        fileReader.onload = function () {#}
{#            //2.登上一部读完文件之后才把文件加载到img标签中#}
{#            $("#avatar-img").attr("src", fileReader.result);#}
{#        };#}
{#    });#}
{#    // AJAX提交注册的数据#}
{#    $("#reg-submit").click(function () {#}
{#        // 取到用户发送的请求数据,向后端发送AJAX请求#}
{#        //var username = $("#id_username").val();#}
{#        //var password = $("#id_password").val();#}
{#        //var re_password = $("#id_re_password").val()#}
{#        //var email = $("#id_email").val();#}
{##}
{#        var formData = new FormData()#}
{#        formData.append("username", $("#id_username").val());#}
{#        formData.append("password", $("#id_password").val());#}
{#        formData.append("re_password", $("#id_re_password").val());#}
{#        formData.append("phone", $("#id_phone").val());#}
{#        formData.append("email", $("#id_email").val());#}
{#        formData.append("avatar", $("#id_avatar")[0].files[0]);#}
{#        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());#}
{#        $.ajax({#}
{#            url:"/reg/",#}
{#            type:"post",#}
{#            processData: false,// 告诉jQuery不要处理我的数据#}
{#            contentType: false,// 告诉jQuery不要设置content类型#}
{#            data:formData,#}
{#            success:function (data) {#}
{#                if(data.status){#}
{#                    //有错误就展示错误#}
{#                    //console.log(data.msg);#}
{#                    //将报错信息写到页面上#}
{#                    $.each(data.msg, function (k,v) {#}
{#                        $("#id_"+k).next("span").text(v[0]).parent().parent().addClass("has-error");#}
{#                    })#}
{#                }else{#}
{#                    //没有错误就跳转到指定页面#}
{#                    location.href = data.msg;#}
{#                }#}
{##}
{#            }#}
{#        });#}
{#        //将所有的input框架定获取焦点事件，将所有的错误信息清空#}
{#        $("form input").focus(function () {#}
{#            $(this).next().text("").parent().parent().removeClass("has-error");#}
{#        })#}
{#    });#}
{#    // 给username input框绑定一个时区焦点的事件， 失去焦点之后就效验用户名是否存在#}
{#    $("#id_username").blur(function() {#}
{#        //$("#id_username").on("input", function () {}) 边写边效验#}
{#        //alert(123);失去焦点就弹窗#}
{#        //取到用户填的值#}
{#        var username = $(this).val();#}
{#        // 发请求#}
{#        $.ajax({#}
{#            url: "/check_username_exist/",#}
{#            type: "get",#}
{#            data: {"username": username},#}
{#            success: function (data) {#}
{#                if (data.status) {#}
{#                    //用户名已被注册#}
{#                    $("#id_username").next().text(data.msg).parent().parent().addClass("has_error");#}
{#                }#}
{#            }#}
{#        })#}
{#    })#}
{#</script>#}
</body>
</html>